# DeepRat configuration file

project_name: &name TestProject
author: Tester
train_videos:
  - /Users/shabo/Desktop/no-dysk.mp4

# Properties injected to the DLC config.yaml
dlc_config:
  # Bodyparts to be tracked
  bodyparts:
  - test
  - test2
  # Skeleton configuration
  skeleton: null
  # Number of frames to label
  numframes2pick: 20

# Properties of the Anipose config.toml
anipose_config:
  project: *name
  nesting: 1
  pipeline:
    videos_raw: videos-raw
  # labeling scheme...specify lines that you want to draw for visualizing labels in videos
  labeling:
    scheme:
      - - head
        - thorax
        - abdomen
      - - thorax
        - leg-1
  filter:
    enabled: true
    medfilt: 13
    offset_threshold: 25
    score_threshold: 0.8
    spline: true
  triangulation:
    cam_regex: 'cam([0-9])'
  calibration:
    board_type: charuco
    board_size:
      - 6
      - 6
    board_marker_bits: 4
    board_marker_dict_number: 50
    board_marker_length: 3
    board_square_side_length: 4
  manual_verification:
    manually_verify: false