# -- DeepRat configuration file --

# Shared properties
project_name: TestProject
author: Tester
training_videos: [
  "/Users/shabo/Desktop/videos-raw/hand-cam1.MOV",
  "/Users/shabo/Desktop/videos-raw/hand-cam2.MOV",
  "/Users/shabo/Desktop/videos-raw/hand-cam3.MOV",
]
calibration_videos: [
  "/Users/shabo/Desktop/calibration/charuco-cam1.MOV",
  "/Users/shabo/Desktop/calibration/charuco-cam2.MOV",
  "/Users/shabo/Desktop/calibration/charuco-cam3.MOV"
]
scheme: [
  ["thuB", "thuM", "thuT"],
  ["indB", "indM", "indT"],
  ["cent", "thuB"],
  ["cent", "indB"]
]
frames: 10

# Properties of the Anipose config.toml
anipose_config:
  # Filter for 2D outliers, replaced by intepolating
  filter:
    enabled: true
    medfilt: 13
    offset_threshold: 25
    score_threshold: 0.8
    # Enables cubic spline interpolation as opposed to linear
    spline: true
  triangulation:
    cam_regex: 'cam([0-9])'
  calibration:
    board_type: charuco
    board_size:
      - 10
      - 7
    # number of bits in the markers, if aruco/charuco
    board_marker_bits: 4
    # number of markers in dictionary, if aruco/charuco
    board_marker_dict_number: 50
    # length of marker side
    board_marker_length: 18.75 # mm
    # If charuco or checkerboard, square side length
    board_square_side_length: 25 # mm
    # If aruco, length of marker separation
    board_marker_separation_length: 1 # mm
    fisheye: true
  manual_verification:
    manually_verify: false